// Generated by jextract

package fr.dufrenoy.hvt.runtime.vulkan;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VkBindHeapInfoEXT {
 *     VkStructureType sType;
 *     const void *pNext;
 *     VkDeviceAddressRangeEXT heapRange;
 *     VkDeviceSize reservedRangeOffset;
 *     VkDeviceSize reservedRangeSize;
 * }
 * }
 */
public class VkBindHeapInfoEXT {

    VkBindHeapInfoEXT() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        vulkan_h.C_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        vulkan_h.C_POINTER.withName("pNext"),
        VkDeviceAddressRangeEXT.layout().withName("heapRange"),
        vulkan_h.C_LONG_LONG.withName("reservedRangeOffset"),
        vulkan_h.C_LONG_LONG.withName("reservedRangeSize")
    ).withName("VkBindHeapInfoEXT");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt sType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final OfInt sType$layout() {
        return sType$LAYOUT;
    }

    private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final long sType$offset() {
        return sType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static int sType(MemorySegment struct) {
        return struct.get(sType$LAYOUT, sType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static void sType(MemorySegment struct, int fieldValue) {
        struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
    }

    private static final AddressLayout pNext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pNext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static final AddressLayout pNext$layout() {
        return pNext$LAYOUT;
    }

    private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static final long pNext$offset() {
        return pNext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static MemorySegment pNext(MemorySegment struct) {
        return struct.get(pNext$LAYOUT, pNext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static void pNext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
    }

    private static final GroupLayout heapRange$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("heapRange"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceAddressRangeEXT heapRange
     * }
     */
    public static final GroupLayout heapRange$layout() {
        return heapRange$LAYOUT;
    }

    private static final long heapRange$OFFSET = $LAYOUT.byteOffset(groupElement("heapRange"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceAddressRangeEXT heapRange
     * }
     */
    public static final long heapRange$offset() {
        return heapRange$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceAddressRangeEXT heapRange
     * }
     */
    public static MemorySegment heapRange(MemorySegment struct) {
        return struct.asSlice(heapRange$OFFSET, heapRange$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceAddressRangeEXT heapRange
     * }
     */
    public static void heapRange(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, heapRange$OFFSET, heapRange$LAYOUT.byteSize());
    }

    private static final OfLong reservedRangeOffset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("reservedRangeOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize reservedRangeOffset
     * }
     */
    public static final OfLong reservedRangeOffset$layout() {
        return reservedRangeOffset$LAYOUT;
    }

    private static final long reservedRangeOffset$OFFSET = $LAYOUT.byteOffset(groupElement("reservedRangeOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize reservedRangeOffset
     * }
     */
    public static final long reservedRangeOffset$offset() {
        return reservedRangeOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize reservedRangeOffset
     * }
     */
    public static long reservedRangeOffset(MemorySegment struct) {
        return struct.get(reservedRangeOffset$LAYOUT, reservedRangeOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize reservedRangeOffset
     * }
     */
    public static void reservedRangeOffset(MemorySegment struct, long fieldValue) {
        struct.set(reservedRangeOffset$LAYOUT, reservedRangeOffset$OFFSET, fieldValue);
    }

    private static final OfLong reservedRangeSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("reservedRangeSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize reservedRangeSize
     * }
     */
    public static final OfLong reservedRangeSize$layout() {
        return reservedRangeSize$LAYOUT;
    }

    private static final long reservedRangeSize$OFFSET = $LAYOUT.byteOffset(groupElement("reservedRangeSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize reservedRangeSize
     * }
     */
    public static final long reservedRangeSize$offset() {
        return reservedRangeSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize reservedRangeSize
     * }
     */
    public static long reservedRangeSize(MemorySegment struct) {
        return struct.get(reservedRangeSize$LAYOUT, reservedRangeSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize reservedRangeSize
     * }
     */
    public static void reservedRangeSize(MemorySegment struct, long fieldValue) {
        struct.set(reservedRangeSize$LAYOUT, reservedRangeSize$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

