// Generated by jextract

package fr.dufrenoy.hvt.runtime.vulkan;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VkCommandBufferInheritanceDescriptorHeapInfoEXT {
 *     VkStructureType sType;
 *     const void *pNext;
 *     const VkBindHeapInfoEXT *pSamplerHeapBindInfo;
 *     const VkBindHeapInfoEXT *pResourceHeapBindInfo;
 * }
 * }
 */
public class VkCommandBufferInheritanceDescriptorHeapInfoEXT {

    VkCommandBufferInheritanceDescriptorHeapInfoEXT() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        vulkan_h.C_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        vulkan_h.C_POINTER.withName("pNext"),
        vulkan_h.C_POINTER.withName("pSamplerHeapBindInfo"),
        vulkan_h.C_POINTER.withName("pResourceHeapBindInfo")
    ).withName("VkCommandBufferInheritanceDescriptorHeapInfoEXT");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt sType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final OfInt sType$layout() {
        return sType$LAYOUT;
    }

    private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final long sType$offset() {
        return sType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static int sType(MemorySegment struct) {
        return struct.get(sType$LAYOUT, sType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static void sType(MemorySegment struct, int fieldValue) {
        struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
    }

    private static final AddressLayout pNext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pNext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static final AddressLayout pNext$layout() {
        return pNext$LAYOUT;
    }

    private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static final long pNext$offset() {
        return pNext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static MemorySegment pNext(MemorySegment struct) {
        return struct.get(pNext$LAYOUT, pNext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static void pNext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
    }

    private static final AddressLayout pSamplerHeapBindInfo$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pSamplerHeapBindInfo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const VkBindHeapInfoEXT *pSamplerHeapBindInfo
     * }
     */
    public static final AddressLayout pSamplerHeapBindInfo$layout() {
        return pSamplerHeapBindInfo$LAYOUT;
    }

    private static final long pSamplerHeapBindInfo$OFFSET = $LAYOUT.byteOffset(groupElement("pSamplerHeapBindInfo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const VkBindHeapInfoEXT *pSamplerHeapBindInfo
     * }
     */
    public static final long pSamplerHeapBindInfo$offset() {
        return pSamplerHeapBindInfo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const VkBindHeapInfoEXT *pSamplerHeapBindInfo
     * }
     */
    public static MemorySegment pSamplerHeapBindInfo(MemorySegment struct) {
        return struct.get(pSamplerHeapBindInfo$LAYOUT, pSamplerHeapBindInfo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const VkBindHeapInfoEXT *pSamplerHeapBindInfo
     * }
     */
    public static void pSamplerHeapBindInfo(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pSamplerHeapBindInfo$LAYOUT, pSamplerHeapBindInfo$OFFSET, fieldValue);
    }

    private static final AddressLayout pResourceHeapBindInfo$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pResourceHeapBindInfo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const VkBindHeapInfoEXT *pResourceHeapBindInfo
     * }
     */
    public static final AddressLayout pResourceHeapBindInfo$layout() {
        return pResourceHeapBindInfo$LAYOUT;
    }

    private static final long pResourceHeapBindInfo$OFFSET = $LAYOUT.byteOffset(groupElement("pResourceHeapBindInfo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const VkBindHeapInfoEXT *pResourceHeapBindInfo
     * }
     */
    public static final long pResourceHeapBindInfo$offset() {
        return pResourceHeapBindInfo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const VkBindHeapInfoEXT *pResourceHeapBindInfo
     * }
     */
    public static MemorySegment pResourceHeapBindInfo(MemorySegment struct) {
        return struct.get(pResourceHeapBindInfo$LAYOUT, pResourceHeapBindInfo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const VkBindHeapInfoEXT *pResourceHeapBindInfo
     * }
     */
    public static void pResourceHeapBindInfo(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pResourceHeapBindInfo$LAYOUT, pResourceHeapBindInfo$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

