// Generated by jextract

package fr.dufrenoy.hvt.runtime.vulkan;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * union VkDescriptorMappingSourceDataEXT {
 *     VkDescriptorMappingSourceConstantOffsetEXT constantOffset;
 *     VkDescriptorMappingSourcePushIndexEXT pushIndex;
 *     VkDescriptorMappingSourceIndirectIndexEXT indirectIndex;
 *     VkDescriptorMappingSourceIndirectIndexArrayEXT indirectIndexArray;
 *     VkDescriptorMappingSourceHeapDataEXT heapData;
 *     uint32_t pushDataOffset;
 *     uint32_t pushAddressOffset;
 *     VkDescriptorMappingSourceIndirectAddressEXT indirectAddress;
 *     VkDescriptorMappingSourceShaderRecordIndexEXT shaderRecordIndex;
 *     uint32_t shaderRecordDataOffset;
 *     uint32_t shaderRecordAddressOffset;
 * }
 * }
 */
public class VkDescriptorMappingSourceDataEXT {

    VkDescriptorMappingSourceDataEXT() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        VkDescriptorMappingSourceConstantOffsetEXT.layout().withName("constantOffset"),
        VkDescriptorMappingSourcePushIndexEXT.layout().withName("pushIndex"),
        VkDescriptorMappingSourceIndirectIndexEXT.layout().withName("indirectIndex"),
        VkDescriptorMappingSourceIndirectIndexArrayEXT.layout().withName("indirectIndexArray"),
        VkDescriptorMappingSourceHeapDataEXT.layout().withName("heapData"),
        vulkan_h.C_INT.withName("pushDataOffset"),
        vulkan_h.C_INT.withName("pushAddressOffset"),
        VkDescriptorMappingSourceIndirectAddressEXT.layout().withName("indirectAddress"),
        VkDescriptorMappingSourceShaderRecordIndexEXT.layout().withName("shaderRecordIndex"),
        vulkan_h.C_INT.withName("shaderRecordDataOffset"),
        vulkan_h.C_INT.withName("shaderRecordAddressOffset")
    ).withName("VkDescriptorMappingSourceDataEXT");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout constantOffset$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("constantOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceConstantOffsetEXT constantOffset
     * }
     */
    public static final GroupLayout constantOffset$layout() {
        return constantOffset$LAYOUT;
    }

    private static final long constantOffset$OFFSET = $LAYOUT.byteOffset(groupElement("constantOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceConstantOffsetEXT constantOffset
     * }
     */
    public static final long constantOffset$offset() {
        return constantOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceConstantOffsetEXT constantOffset
     * }
     */
    public static MemorySegment constantOffset(MemorySegment union) {
        return union.asSlice(constantOffset$OFFSET, constantOffset$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceConstantOffsetEXT constantOffset
     * }
     */
    public static void constantOffset(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, constantOffset$OFFSET, constantOffset$LAYOUT.byteSize());
    }

    private static final GroupLayout pushIndex$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("pushIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourcePushIndexEXT pushIndex
     * }
     */
    public static final GroupLayout pushIndex$layout() {
        return pushIndex$LAYOUT;
    }

    private static final long pushIndex$OFFSET = $LAYOUT.byteOffset(groupElement("pushIndex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourcePushIndexEXT pushIndex
     * }
     */
    public static final long pushIndex$offset() {
        return pushIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourcePushIndexEXT pushIndex
     * }
     */
    public static MemorySegment pushIndex(MemorySegment union) {
        return union.asSlice(pushIndex$OFFSET, pushIndex$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourcePushIndexEXT pushIndex
     * }
     */
    public static void pushIndex(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, pushIndex$OFFSET, pushIndex$LAYOUT.byteSize());
    }

    private static final GroupLayout indirectIndex$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("indirectIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectIndexEXT indirectIndex
     * }
     */
    public static final GroupLayout indirectIndex$layout() {
        return indirectIndex$LAYOUT;
    }

    private static final long indirectIndex$OFFSET = $LAYOUT.byteOffset(groupElement("indirectIndex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectIndexEXT indirectIndex
     * }
     */
    public static final long indirectIndex$offset() {
        return indirectIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectIndexEXT indirectIndex
     * }
     */
    public static MemorySegment indirectIndex(MemorySegment union) {
        return union.asSlice(indirectIndex$OFFSET, indirectIndex$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectIndexEXT indirectIndex
     * }
     */
    public static void indirectIndex(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, indirectIndex$OFFSET, indirectIndex$LAYOUT.byteSize());
    }

    private static final GroupLayout indirectIndexArray$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("indirectIndexArray"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectIndexArrayEXT indirectIndexArray
     * }
     */
    public static final GroupLayout indirectIndexArray$layout() {
        return indirectIndexArray$LAYOUT;
    }

    private static final long indirectIndexArray$OFFSET = $LAYOUT.byteOffset(groupElement("indirectIndexArray"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectIndexArrayEXT indirectIndexArray
     * }
     */
    public static final long indirectIndexArray$offset() {
        return indirectIndexArray$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectIndexArrayEXT indirectIndexArray
     * }
     */
    public static MemorySegment indirectIndexArray(MemorySegment union) {
        return union.asSlice(indirectIndexArray$OFFSET, indirectIndexArray$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectIndexArrayEXT indirectIndexArray
     * }
     */
    public static void indirectIndexArray(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, indirectIndexArray$OFFSET, indirectIndexArray$LAYOUT.byteSize());
    }

    private static final GroupLayout heapData$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("heapData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceHeapDataEXT heapData
     * }
     */
    public static final GroupLayout heapData$layout() {
        return heapData$LAYOUT;
    }

    private static final long heapData$OFFSET = $LAYOUT.byteOffset(groupElement("heapData"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceHeapDataEXT heapData
     * }
     */
    public static final long heapData$offset() {
        return heapData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceHeapDataEXT heapData
     * }
     */
    public static MemorySegment heapData(MemorySegment union) {
        return union.asSlice(heapData$OFFSET, heapData$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceHeapDataEXT heapData
     * }
     */
    public static void heapData(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, heapData$OFFSET, heapData$LAYOUT.byteSize());
    }

    private static final OfInt pushDataOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pushDataOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t pushDataOffset
     * }
     */
    public static final OfInt pushDataOffset$layout() {
        return pushDataOffset$LAYOUT;
    }

    private static final long pushDataOffset$OFFSET = $LAYOUT.byteOffset(groupElement("pushDataOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t pushDataOffset
     * }
     */
    public static final long pushDataOffset$offset() {
        return pushDataOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t pushDataOffset
     * }
     */
    public static int pushDataOffset(MemorySegment union) {
        return union.get(pushDataOffset$LAYOUT, pushDataOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t pushDataOffset
     * }
     */
    public static void pushDataOffset(MemorySegment union, int fieldValue) {
        union.set(pushDataOffset$LAYOUT, pushDataOffset$OFFSET, fieldValue);
    }

    private static final OfInt pushAddressOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pushAddressOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t pushAddressOffset
     * }
     */
    public static final OfInt pushAddressOffset$layout() {
        return pushAddressOffset$LAYOUT;
    }

    private static final long pushAddressOffset$OFFSET = $LAYOUT.byteOffset(groupElement("pushAddressOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t pushAddressOffset
     * }
     */
    public static final long pushAddressOffset$offset() {
        return pushAddressOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t pushAddressOffset
     * }
     */
    public static int pushAddressOffset(MemorySegment union) {
        return union.get(pushAddressOffset$LAYOUT, pushAddressOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t pushAddressOffset
     * }
     */
    public static void pushAddressOffset(MemorySegment union, int fieldValue) {
        union.set(pushAddressOffset$LAYOUT, pushAddressOffset$OFFSET, fieldValue);
    }

    private static final GroupLayout indirectAddress$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("indirectAddress"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectAddressEXT indirectAddress
     * }
     */
    public static final GroupLayout indirectAddress$layout() {
        return indirectAddress$LAYOUT;
    }

    private static final long indirectAddress$OFFSET = $LAYOUT.byteOffset(groupElement("indirectAddress"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectAddressEXT indirectAddress
     * }
     */
    public static final long indirectAddress$offset() {
        return indirectAddress$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectAddressEXT indirectAddress
     * }
     */
    public static MemorySegment indirectAddress(MemorySegment union) {
        return union.asSlice(indirectAddress$OFFSET, indirectAddress$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceIndirectAddressEXT indirectAddress
     * }
     */
    public static void indirectAddress(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, indirectAddress$OFFSET, indirectAddress$LAYOUT.byteSize());
    }

    private static final GroupLayout shaderRecordIndex$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("shaderRecordIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceShaderRecordIndexEXT shaderRecordIndex
     * }
     */
    public static final GroupLayout shaderRecordIndex$layout() {
        return shaderRecordIndex$LAYOUT;
    }

    private static final long shaderRecordIndex$OFFSET = $LAYOUT.byteOffset(groupElement("shaderRecordIndex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceShaderRecordIndexEXT shaderRecordIndex
     * }
     */
    public static final long shaderRecordIndex$offset() {
        return shaderRecordIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceShaderRecordIndexEXT shaderRecordIndex
     * }
     */
    public static MemorySegment shaderRecordIndex(MemorySegment union) {
        return union.asSlice(shaderRecordIndex$OFFSET, shaderRecordIndex$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceShaderRecordIndexEXT shaderRecordIndex
     * }
     */
    public static void shaderRecordIndex(MemorySegment union, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, union, shaderRecordIndex$OFFSET, shaderRecordIndex$LAYOUT.byteSize());
    }

    private static final OfInt shaderRecordDataOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("shaderRecordDataOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordDataOffset
     * }
     */
    public static final OfInt shaderRecordDataOffset$layout() {
        return shaderRecordDataOffset$LAYOUT;
    }

    private static final long shaderRecordDataOffset$OFFSET = $LAYOUT.byteOffset(groupElement("shaderRecordDataOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordDataOffset
     * }
     */
    public static final long shaderRecordDataOffset$offset() {
        return shaderRecordDataOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordDataOffset
     * }
     */
    public static int shaderRecordDataOffset(MemorySegment union) {
        return union.get(shaderRecordDataOffset$LAYOUT, shaderRecordDataOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordDataOffset
     * }
     */
    public static void shaderRecordDataOffset(MemorySegment union, int fieldValue) {
        union.set(shaderRecordDataOffset$LAYOUT, shaderRecordDataOffset$OFFSET, fieldValue);
    }

    private static final OfInt shaderRecordAddressOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("shaderRecordAddressOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordAddressOffset
     * }
     */
    public static final OfInt shaderRecordAddressOffset$layout() {
        return shaderRecordAddressOffset$LAYOUT;
    }

    private static final long shaderRecordAddressOffset$OFFSET = $LAYOUT.byteOffset(groupElement("shaderRecordAddressOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordAddressOffset
     * }
     */
    public static final long shaderRecordAddressOffset$offset() {
        return shaderRecordAddressOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordAddressOffset
     * }
     */
    public static int shaderRecordAddressOffset(MemorySegment union) {
        return union.get(shaderRecordAddressOffset$LAYOUT, shaderRecordAddressOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordAddressOffset
     * }
     */
    public static void shaderRecordAddressOffset(MemorySegment union, int fieldValue) {
        union.set(shaderRecordAddressOffset$LAYOUT, shaderRecordAddressOffset$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this union
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

