// Generated by jextract

package fr.dufrenoy.hvt.runtime.vulkan;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VkDescriptorSetAndBindingMappingEXT {
 *     VkStructureType sType;
 *     const void *pNext;
 *     uint32_t descriptorSet;
 *     uint32_t firstBinding;
 *     uint32_t bindingCount;
 *     VkSpirvResourceTypeFlagsEXT resourceMask;
 *     VkDescriptorMappingSourceEXT source;
 *     VkDescriptorMappingSourceDataEXT sourceData;
 * }
 * }
 */
public class VkDescriptorSetAndBindingMappingEXT {

    VkDescriptorSetAndBindingMappingEXT() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        vulkan_h.C_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        vulkan_h.C_POINTER.withName("pNext"),
        vulkan_h.C_INT.withName("descriptorSet"),
        vulkan_h.C_INT.withName("firstBinding"),
        vulkan_h.C_INT.withName("bindingCount"),
        vulkan_h.C_INT.withName("resourceMask"),
        vulkan_h.C_INT.withName("source"),
        MemoryLayout.paddingLayout(4),
        VkDescriptorMappingSourceDataEXT.layout().withName("sourceData")
    ).withName("VkDescriptorSetAndBindingMappingEXT");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt sType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final OfInt sType$layout() {
        return sType$LAYOUT;
    }

    private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final long sType$offset() {
        return sType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static int sType(MemorySegment struct) {
        return struct.get(sType$LAYOUT, sType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static void sType(MemorySegment struct, int fieldValue) {
        struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
    }

    private static final AddressLayout pNext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pNext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static final AddressLayout pNext$layout() {
        return pNext$LAYOUT;
    }

    private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static final long pNext$offset() {
        return pNext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static MemorySegment pNext(MemorySegment struct) {
        return struct.get(pNext$LAYOUT, pNext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const void *pNext
     * }
     */
    public static void pNext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
    }

    private static final OfInt descriptorSet$LAYOUT = (OfInt)$LAYOUT.select(groupElement("descriptorSet"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t descriptorSet
     * }
     */
    public static final OfInt descriptorSet$layout() {
        return descriptorSet$LAYOUT;
    }

    private static final long descriptorSet$OFFSET = $LAYOUT.byteOffset(groupElement("descriptorSet"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t descriptorSet
     * }
     */
    public static final long descriptorSet$offset() {
        return descriptorSet$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t descriptorSet
     * }
     */
    public static int descriptorSet(MemorySegment struct) {
        return struct.get(descriptorSet$LAYOUT, descriptorSet$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t descriptorSet
     * }
     */
    public static void descriptorSet(MemorySegment struct, int fieldValue) {
        struct.set(descriptorSet$LAYOUT, descriptorSet$OFFSET, fieldValue);
    }

    private static final OfInt firstBinding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("firstBinding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t firstBinding
     * }
     */
    public static final OfInt firstBinding$layout() {
        return firstBinding$LAYOUT;
    }

    private static final long firstBinding$OFFSET = $LAYOUT.byteOffset(groupElement("firstBinding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t firstBinding
     * }
     */
    public static final long firstBinding$offset() {
        return firstBinding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t firstBinding
     * }
     */
    public static int firstBinding(MemorySegment struct) {
        return struct.get(firstBinding$LAYOUT, firstBinding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t firstBinding
     * }
     */
    public static void firstBinding(MemorySegment struct, int fieldValue) {
        struct.set(firstBinding$LAYOUT, firstBinding$OFFSET, fieldValue);
    }

    private static final OfInt bindingCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bindingCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t bindingCount
     * }
     */
    public static final OfInt bindingCount$layout() {
        return bindingCount$LAYOUT;
    }

    private static final long bindingCount$OFFSET = $LAYOUT.byteOffset(groupElement("bindingCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t bindingCount
     * }
     */
    public static final long bindingCount$offset() {
        return bindingCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t bindingCount
     * }
     */
    public static int bindingCount(MemorySegment struct) {
        return struct.get(bindingCount$LAYOUT, bindingCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t bindingCount
     * }
     */
    public static void bindingCount(MemorySegment struct, int fieldValue) {
        struct.set(bindingCount$LAYOUT, bindingCount$OFFSET, fieldValue);
    }

    private static final OfInt resourceMask$LAYOUT = (OfInt)$LAYOUT.select(groupElement("resourceMask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkSpirvResourceTypeFlagsEXT resourceMask
     * }
     */
    public static final OfInt resourceMask$layout() {
        return resourceMask$LAYOUT;
    }

    private static final long resourceMask$OFFSET = $LAYOUT.byteOffset(groupElement("resourceMask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkSpirvResourceTypeFlagsEXT resourceMask
     * }
     */
    public static final long resourceMask$offset() {
        return resourceMask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkSpirvResourceTypeFlagsEXT resourceMask
     * }
     */
    public static int resourceMask(MemorySegment struct) {
        return struct.get(resourceMask$LAYOUT, resourceMask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkSpirvResourceTypeFlagsEXT resourceMask
     * }
     */
    public static void resourceMask(MemorySegment struct, int fieldValue) {
        struct.set(resourceMask$LAYOUT, resourceMask$OFFSET, fieldValue);
    }

    private static final OfInt source$LAYOUT = (OfInt)$LAYOUT.select(groupElement("source"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceEXT source
     * }
     */
    public static final OfInt source$layout() {
        return source$LAYOUT;
    }

    private static final long source$OFFSET = $LAYOUT.byteOffset(groupElement("source"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceEXT source
     * }
     */
    public static final long source$offset() {
        return source$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceEXT source
     * }
     */
    public static int source(MemorySegment struct) {
        return struct.get(source$LAYOUT, source$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceEXT source
     * }
     */
    public static void source(MemorySegment struct, int fieldValue) {
        struct.set(source$LAYOUT, source$OFFSET, fieldValue);
    }

    private static final GroupLayout sourceData$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("sourceData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceDataEXT sourceData
     * }
     */
    public static final GroupLayout sourceData$layout() {
        return sourceData$LAYOUT;
    }

    private static final long sourceData$OFFSET = $LAYOUT.byteOffset(groupElement("sourceData"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceDataEXT sourceData
     * }
     */
    public static final long sourceData$offset() {
        return sourceData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceDataEXT sourceData
     * }
     */
    public static MemorySegment sourceData(MemorySegment struct) {
        return struct.asSlice(sourceData$OFFSET, sourceData$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDescriptorMappingSourceDataEXT sourceData
     * }
     */
    public static void sourceData(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, sourceData$OFFSET, sourceData$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

