// Generated by jextract

package fr.dufrenoy.hvt.runtime.vulkan;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VkDescriptorMappingSourceIndirectAddressEXT {
 *     uint32_t pushOffset;
 *     uint32_t addressOffset;
 * }
 * }
 */
public class VkDescriptorMappingSourceIndirectAddressEXT {

    VkDescriptorMappingSourceIndirectAddressEXT() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        vulkan_h.C_INT.withName("pushOffset"),
        vulkan_h.C_INT.withName("addressOffset")
    ).withName("VkDescriptorMappingSourceIndirectAddressEXT");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt pushOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pushOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t pushOffset
     * }
     */
    public static final OfInt pushOffset$layout() {
        return pushOffset$LAYOUT;
    }

    private static final long pushOffset$OFFSET = $LAYOUT.byteOffset(groupElement("pushOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t pushOffset
     * }
     */
    public static final long pushOffset$offset() {
        return pushOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t pushOffset
     * }
     */
    public static int pushOffset(MemorySegment struct) {
        return struct.get(pushOffset$LAYOUT, pushOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t pushOffset
     * }
     */
    public static void pushOffset(MemorySegment struct, int fieldValue) {
        struct.set(pushOffset$LAYOUT, pushOffset$OFFSET, fieldValue);
    }

    private static final OfInt addressOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("addressOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t addressOffset
     * }
     */
    public static final OfInt addressOffset$layout() {
        return addressOffset$LAYOUT;
    }

    private static final long addressOffset$OFFSET = $LAYOUT.byteOffset(groupElement("addressOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t addressOffset
     * }
     */
    public static final long addressOffset$offset() {
        return addressOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t addressOffset
     * }
     */
    public static int addressOffset(MemorySegment struct) {
        return struct.get(addressOffset$LAYOUT, addressOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t addressOffset
     * }
     */
    public static void addressOffset(MemorySegment struct, int fieldValue) {
        struct.set(addressOffset$LAYOUT, addressOffset$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

