// Generated by jextract

package fr.dufrenoy.hvt.runtime.vulkan;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VkDescriptorMappingSourceShaderRecordIndexEXT {
 *     uint32_t heapOffset;
 *     uint32_t shaderRecordOffset;
 *     uint32_t heapIndexStride;
 *     uint32_t heapArrayStride;
 *     const VkSamplerCreateInfo *pEmbeddedSampler;
 *     VkBool32 useCombinedImageSamplerIndex;
 *     uint32_t samplerHeapOffset;
 *     uint32_t samplerShaderRecordOffset;
 *     uint32_t samplerHeapIndexStride;
 *     uint32_t samplerHeapArrayStride;
 * }
 * }
 */
public class VkDescriptorMappingSourceShaderRecordIndexEXT {

    VkDescriptorMappingSourceShaderRecordIndexEXT() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        vulkan_h.C_INT.withName("heapOffset"),
        vulkan_h.C_INT.withName("shaderRecordOffset"),
        vulkan_h.C_INT.withName("heapIndexStride"),
        vulkan_h.C_INT.withName("heapArrayStride"),
        vulkan_h.C_POINTER.withName("pEmbeddedSampler"),
        vulkan_h.C_INT.withName("useCombinedImageSamplerIndex"),
        vulkan_h.C_INT.withName("samplerHeapOffset"),
        vulkan_h.C_INT.withName("samplerShaderRecordOffset"),
        vulkan_h.C_INT.withName("samplerHeapIndexStride"),
        vulkan_h.C_INT.withName("samplerHeapArrayStride"),
        MemoryLayout.paddingLayout(4)
    ).withName("VkDescriptorMappingSourceShaderRecordIndexEXT");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt heapOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("heapOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t heapOffset
     * }
     */
    public static final OfInt heapOffset$layout() {
        return heapOffset$LAYOUT;
    }

    private static final long heapOffset$OFFSET = $LAYOUT.byteOffset(groupElement("heapOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t heapOffset
     * }
     */
    public static final long heapOffset$offset() {
        return heapOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t heapOffset
     * }
     */
    public static int heapOffset(MemorySegment struct) {
        return struct.get(heapOffset$LAYOUT, heapOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t heapOffset
     * }
     */
    public static void heapOffset(MemorySegment struct, int fieldValue) {
        struct.set(heapOffset$LAYOUT, heapOffset$OFFSET, fieldValue);
    }

    private static final OfInt shaderRecordOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("shaderRecordOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordOffset
     * }
     */
    public static final OfInt shaderRecordOffset$layout() {
        return shaderRecordOffset$LAYOUT;
    }

    private static final long shaderRecordOffset$OFFSET = $LAYOUT.byteOffset(groupElement("shaderRecordOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordOffset
     * }
     */
    public static final long shaderRecordOffset$offset() {
        return shaderRecordOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordOffset
     * }
     */
    public static int shaderRecordOffset(MemorySegment struct) {
        return struct.get(shaderRecordOffset$LAYOUT, shaderRecordOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t shaderRecordOffset
     * }
     */
    public static void shaderRecordOffset(MemorySegment struct, int fieldValue) {
        struct.set(shaderRecordOffset$LAYOUT, shaderRecordOffset$OFFSET, fieldValue);
    }

    private static final OfInt heapIndexStride$LAYOUT = (OfInt)$LAYOUT.select(groupElement("heapIndexStride"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t heapIndexStride
     * }
     */
    public static final OfInt heapIndexStride$layout() {
        return heapIndexStride$LAYOUT;
    }

    private static final long heapIndexStride$OFFSET = $LAYOUT.byteOffset(groupElement("heapIndexStride"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t heapIndexStride
     * }
     */
    public static final long heapIndexStride$offset() {
        return heapIndexStride$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t heapIndexStride
     * }
     */
    public static int heapIndexStride(MemorySegment struct) {
        return struct.get(heapIndexStride$LAYOUT, heapIndexStride$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t heapIndexStride
     * }
     */
    public static void heapIndexStride(MemorySegment struct, int fieldValue) {
        struct.set(heapIndexStride$LAYOUT, heapIndexStride$OFFSET, fieldValue);
    }

    private static final OfInt heapArrayStride$LAYOUT = (OfInt)$LAYOUT.select(groupElement("heapArrayStride"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t heapArrayStride
     * }
     */
    public static final OfInt heapArrayStride$layout() {
        return heapArrayStride$LAYOUT;
    }

    private static final long heapArrayStride$OFFSET = $LAYOUT.byteOffset(groupElement("heapArrayStride"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t heapArrayStride
     * }
     */
    public static final long heapArrayStride$offset() {
        return heapArrayStride$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t heapArrayStride
     * }
     */
    public static int heapArrayStride(MemorySegment struct) {
        return struct.get(heapArrayStride$LAYOUT, heapArrayStride$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t heapArrayStride
     * }
     */
    public static void heapArrayStride(MemorySegment struct, int fieldValue) {
        struct.set(heapArrayStride$LAYOUT, heapArrayStride$OFFSET, fieldValue);
    }

    private static final AddressLayout pEmbeddedSampler$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pEmbeddedSampler"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const VkSamplerCreateInfo *pEmbeddedSampler
     * }
     */
    public static final AddressLayout pEmbeddedSampler$layout() {
        return pEmbeddedSampler$LAYOUT;
    }

    private static final long pEmbeddedSampler$OFFSET = $LAYOUT.byteOffset(groupElement("pEmbeddedSampler"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const VkSamplerCreateInfo *pEmbeddedSampler
     * }
     */
    public static final long pEmbeddedSampler$offset() {
        return pEmbeddedSampler$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const VkSamplerCreateInfo *pEmbeddedSampler
     * }
     */
    public static MemorySegment pEmbeddedSampler(MemorySegment struct) {
        return struct.get(pEmbeddedSampler$LAYOUT, pEmbeddedSampler$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const VkSamplerCreateInfo *pEmbeddedSampler
     * }
     */
    public static void pEmbeddedSampler(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pEmbeddedSampler$LAYOUT, pEmbeddedSampler$OFFSET, fieldValue);
    }

    private static final OfInt useCombinedImageSamplerIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("useCombinedImageSamplerIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkBool32 useCombinedImageSamplerIndex
     * }
     */
    public static final OfInt useCombinedImageSamplerIndex$layout() {
        return useCombinedImageSamplerIndex$LAYOUT;
    }

    private static final long useCombinedImageSamplerIndex$OFFSET = $LAYOUT.byteOffset(groupElement("useCombinedImageSamplerIndex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkBool32 useCombinedImageSamplerIndex
     * }
     */
    public static final long useCombinedImageSamplerIndex$offset() {
        return useCombinedImageSamplerIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkBool32 useCombinedImageSamplerIndex
     * }
     */
    public static int useCombinedImageSamplerIndex(MemorySegment struct) {
        return struct.get(useCombinedImageSamplerIndex$LAYOUT, useCombinedImageSamplerIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkBool32 useCombinedImageSamplerIndex
     * }
     */
    public static void useCombinedImageSamplerIndex(MemorySegment struct, int fieldValue) {
        struct.set(useCombinedImageSamplerIndex$LAYOUT, useCombinedImageSamplerIndex$OFFSET, fieldValue);
    }

    private static final OfInt samplerHeapOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("samplerHeapOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapOffset
     * }
     */
    public static final OfInt samplerHeapOffset$layout() {
        return samplerHeapOffset$LAYOUT;
    }

    private static final long samplerHeapOffset$OFFSET = $LAYOUT.byteOffset(groupElement("samplerHeapOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapOffset
     * }
     */
    public static final long samplerHeapOffset$offset() {
        return samplerHeapOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapOffset
     * }
     */
    public static int samplerHeapOffset(MemorySegment struct) {
        return struct.get(samplerHeapOffset$LAYOUT, samplerHeapOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapOffset
     * }
     */
    public static void samplerHeapOffset(MemorySegment struct, int fieldValue) {
        struct.set(samplerHeapOffset$LAYOUT, samplerHeapOffset$OFFSET, fieldValue);
    }

    private static final OfInt samplerShaderRecordOffset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("samplerShaderRecordOffset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t samplerShaderRecordOffset
     * }
     */
    public static final OfInt samplerShaderRecordOffset$layout() {
        return samplerShaderRecordOffset$LAYOUT;
    }

    private static final long samplerShaderRecordOffset$OFFSET = $LAYOUT.byteOffset(groupElement("samplerShaderRecordOffset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t samplerShaderRecordOffset
     * }
     */
    public static final long samplerShaderRecordOffset$offset() {
        return samplerShaderRecordOffset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t samplerShaderRecordOffset
     * }
     */
    public static int samplerShaderRecordOffset(MemorySegment struct) {
        return struct.get(samplerShaderRecordOffset$LAYOUT, samplerShaderRecordOffset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t samplerShaderRecordOffset
     * }
     */
    public static void samplerShaderRecordOffset(MemorySegment struct, int fieldValue) {
        struct.set(samplerShaderRecordOffset$LAYOUT, samplerShaderRecordOffset$OFFSET, fieldValue);
    }

    private static final OfInt samplerHeapIndexStride$LAYOUT = (OfInt)$LAYOUT.select(groupElement("samplerHeapIndexStride"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapIndexStride
     * }
     */
    public static final OfInt samplerHeapIndexStride$layout() {
        return samplerHeapIndexStride$LAYOUT;
    }

    private static final long samplerHeapIndexStride$OFFSET = $LAYOUT.byteOffset(groupElement("samplerHeapIndexStride"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapIndexStride
     * }
     */
    public static final long samplerHeapIndexStride$offset() {
        return samplerHeapIndexStride$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapIndexStride
     * }
     */
    public static int samplerHeapIndexStride(MemorySegment struct) {
        return struct.get(samplerHeapIndexStride$LAYOUT, samplerHeapIndexStride$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapIndexStride
     * }
     */
    public static void samplerHeapIndexStride(MemorySegment struct, int fieldValue) {
        struct.set(samplerHeapIndexStride$LAYOUT, samplerHeapIndexStride$OFFSET, fieldValue);
    }

    private static final OfInt samplerHeapArrayStride$LAYOUT = (OfInt)$LAYOUT.select(groupElement("samplerHeapArrayStride"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapArrayStride
     * }
     */
    public static final OfInt samplerHeapArrayStride$layout() {
        return samplerHeapArrayStride$LAYOUT;
    }

    private static final long samplerHeapArrayStride$OFFSET = $LAYOUT.byteOffset(groupElement("samplerHeapArrayStride"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapArrayStride
     * }
     */
    public static final long samplerHeapArrayStride$offset() {
        return samplerHeapArrayStride$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapArrayStride
     * }
     */
    public static int samplerHeapArrayStride(MemorySegment struct) {
        return struct.get(samplerHeapArrayStride$LAYOUT, samplerHeapArrayStride$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t samplerHeapArrayStride
     * }
     */
    public static void samplerHeapArrayStride(MemorySegment struct, int fieldValue) {
        struct.set(samplerHeapArrayStride$LAYOUT, samplerHeapArrayStride$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

