// Generated by jextract

package fr.dufrenoy.hvt.runtime.vulkan;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VkPhysicalDevicePushConstantBankPropertiesNV {
 *     VkStructureType sType;
 *     void *pNext;
 *     uint32_t maxGraphicsPushConstantBanks;
 *     uint32_t maxComputePushConstantBanks;
 *     uint32_t maxGraphicsPushDataBanks;
 *     uint32_t maxComputePushDataBanks;
 * }
 * }
 */
public class VkPhysicalDevicePushConstantBankPropertiesNV {

    VkPhysicalDevicePushConstantBankPropertiesNV() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        vulkan_h.C_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        vulkan_h.C_POINTER.withName("pNext"),
        vulkan_h.C_INT.withName("maxGraphicsPushConstantBanks"),
        vulkan_h.C_INT.withName("maxComputePushConstantBanks"),
        vulkan_h.C_INT.withName("maxGraphicsPushDataBanks"),
        vulkan_h.C_INT.withName("maxComputePushDataBanks")
    ).withName("VkPhysicalDevicePushConstantBankPropertiesNV");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt sType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final OfInt sType$layout() {
        return sType$LAYOUT;
    }

    private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final long sType$offset() {
        return sType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static int sType(MemorySegment struct) {
        return struct.get(sType$LAYOUT, sType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static void sType(MemorySegment struct, int fieldValue) {
        struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
    }

    private static final AddressLayout pNext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pNext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static final AddressLayout pNext$layout() {
        return pNext$LAYOUT;
    }

    private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static final long pNext$offset() {
        return pNext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static MemorySegment pNext(MemorySegment struct) {
        return struct.get(pNext$LAYOUT, pNext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static void pNext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
    }

    private static final OfInt maxGraphicsPushConstantBanks$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maxGraphicsPushConstantBanks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t maxGraphicsPushConstantBanks
     * }
     */
    public static final OfInt maxGraphicsPushConstantBanks$layout() {
        return maxGraphicsPushConstantBanks$LAYOUT;
    }

    private static final long maxGraphicsPushConstantBanks$OFFSET = $LAYOUT.byteOffset(groupElement("maxGraphicsPushConstantBanks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t maxGraphicsPushConstantBanks
     * }
     */
    public static final long maxGraphicsPushConstantBanks$offset() {
        return maxGraphicsPushConstantBanks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t maxGraphicsPushConstantBanks
     * }
     */
    public static int maxGraphicsPushConstantBanks(MemorySegment struct) {
        return struct.get(maxGraphicsPushConstantBanks$LAYOUT, maxGraphicsPushConstantBanks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t maxGraphicsPushConstantBanks
     * }
     */
    public static void maxGraphicsPushConstantBanks(MemorySegment struct, int fieldValue) {
        struct.set(maxGraphicsPushConstantBanks$LAYOUT, maxGraphicsPushConstantBanks$OFFSET, fieldValue);
    }

    private static final OfInt maxComputePushConstantBanks$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maxComputePushConstantBanks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t maxComputePushConstantBanks
     * }
     */
    public static final OfInt maxComputePushConstantBanks$layout() {
        return maxComputePushConstantBanks$LAYOUT;
    }

    private static final long maxComputePushConstantBanks$OFFSET = $LAYOUT.byteOffset(groupElement("maxComputePushConstantBanks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t maxComputePushConstantBanks
     * }
     */
    public static final long maxComputePushConstantBanks$offset() {
        return maxComputePushConstantBanks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t maxComputePushConstantBanks
     * }
     */
    public static int maxComputePushConstantBanks(MemorySegment struct) {
        return struct.get(maxComputePushConstantBanks$LAYOUT, maxComputePushConstantBanks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t maxComputePushConstantBanks
     * }
     */
    public static void maxComputePushConstantBanks(MemorySegment struct, int fieldValue) {
        struct.set(maxComputePushConstantBanks$LAYOUT, maxComputePushConstantBanks$OFFSET, fieldValue);
    }

    private static final OfInt maxGraphicsPushDataBanks$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maxGraphicsPushDataBanks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t maxGraphicsPushDataBanks
     * }
     */
    public static final OfInt maxGraphicsPushDataBanks$layout() {
        return maxGraphicsPushDataBanks$LAYOUT;
    }

    private static final long maxGraphicsPushDataBanks$OFFSET = $LAYOUT.byteOffset(groupElement("maxGraphicsPushDataBanks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t maxGraphicsPushDataBanks
     * }
     */
    public static final long maxGraphicsPushDataBanks$offset() {
        return maxGraphicsPushDataBanks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t maxGraphicsPushDataBanks
     * }
     */
    public static int maxGraphicsPushDataBanks(MemorySegment struct) {
        return struct.get(maxGraphicsPushDataBanks$LAYOUT, maxGraphicsPushDataBanks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t maxGraphicsPushDataBanks
     * }
     */
    public static void maxGraphicsPushDataBanks(MemorySegment struct, int fieldValue) {
        struct.set(maxGraphicsPushDataBanks$LAYOUT, maxGraphicsPushDataBanks$OFFSET, fieldValue);
    }

    private static final OfInt maxComputePushDataBanks$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maxComputePushDataBanks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t maxComputePushDataBanks
     * }
     */
    public static final OfInt maxComputePushDataBanks$layout() {
        return maxComputePushDataBanks$LAYOUT;
    }

    private static final long maxComputePushDataBanks$OFFSET = $LAYOUT.byteOffset(groupElement("maxComputePushDataBanks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t maxComputePushDataBanks
     * }
     */
    public static final long maxComputePushDataBanks$offset() {
        return maxComputePushDataBanks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t maxComputePushDataBanks
     * }
     */
    public static int maxComputePushDataBanks(MemorySegment struct) {
        return struct.get(maxComputePushDataBanks$LAYOUT, maxComputePushDataBanks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t maxComputePushDataBanks
     * }
     */
    public static void maxComputePushDataBanks(MemorySegment struct, int fieldValue) {
        struct.set(maxComputePushDataBanks$LAYOUT, maxComputePushDataBanks$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

