// Generated by jextract

package fr.dufrenoy.hvt.runtime.vulkan;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VkPhysicalDeviceDescriptorHeapTensorPropertiesARM {
 *     VkStructureType sType;
 *     void *pNext;
 *     VkDeviceSize tensorDescriptorSize;
 *     VkDeviceSize tensorDescriptorAlignment;
 *     size_t tensorCaptureReplayOpaqueDataSize;
 * }
 * }
 */
public class VkPhysicalDeviceDescriptorHeapTensorPropertiesARM {

    VkPhysicalDeviceDescriptorHeapTensorPropertiesARM() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        vulkan_h.C_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        vulkan_h.C_POINTER.withName("pNext"),
        vulkan_h.C_LONG_LONG.withName("tensorDescriptorSize"),
        vulkan_h.C_LONG_LONG.withName("tensorDescriptorAlignment"),
        vulkan_h.C_LONG_LONG.withName("tensorCaptureReplayOpaqueDataSize")
    ).withName("VkPhysicalDeviceDescriptorHeapTensorPropertiesARM");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt sType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final OfInt sType$layout() {
        return sType$LAYOUT;
    }

    private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final long sType$offset() {
        return sType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static int sType(MemorySegment struct) {
        return struct.get(sType$LAYOUT, sType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static void sType(MemorySegment struct, int fieldValue) {
        struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
    }

    private static final AddressLayout pNext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pNext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static final AddressLayout pNext$layout() {
        return pNext$LAYOUT;
    }

    private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static final long pNext$offset() {
        return pNext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static MemorySegment pNext(MemorySegment struct) {
        return struct.get(pNext$LAYOUT, pNext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static void pNext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
    }

    private static final OfLong tensorDescriptorSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("tensorDescriptorSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize tensorDescriptorSize
     * }
     */
    public static final OfLong tensorDescriptorSize$layout() {
        return tensorDescriptorSize$LAYOUT;
    }

    private static final long tensorDescriptorSize$OFFSET = $LAYOUT.byteOffset(groupElement("tensorDescriptorSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize tensorDescriptorSize
     * }
     */
    public static final long tensorDescriptorSize$offset() {
        return tensorDescriptorSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize tensorDescriptorSize
     * }
     */
    public static long tensorDescriptorSize(MemorySegment struct) {
        return struct.get(tensorDescriptorSize$LAYOUT, tensorDescriptorSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize tensorDescriptorSize
     * }
     */
    public static void tensorDescriptorSize(MemorySegment struct, long fieldValue) {
        struct.set(tensorDescriptorSize$LAYOUT, tensorDescriptorSize$OFFSET, fieldValue);
    }

    private static final OfLong tensorDescriptorAlignment$LAYOUT = (OfLong)$LAYOUT.select(groupElement("tensorDescriptorAlignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize tensorDescriptorAlignment
     * }
     */
    public static final OfLong tensorDescriptorAlignment$layout() {
        return tensorDescriptorAlignment$LAYOUT;
    }

    private static final long tensorDescriptorAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("tensorDescriptorAlignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize tensorDescriptorAlignment
     * }
     */
    public static final long tensorDescriptorAlignment$offset() {
        return tensorDescriptorAlignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize tensorDescriptorAlignment
     * }
     */
    public static long tensorDescriptorAlignment(MemorySegment struct) {
        return struct.get(tensorDescriptorAlignment$LAYOUT, tensorDescriptorAlignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize tensorDescriptorAlignment
     * }
     */
    public static void tensorDescriptorAlignment(MemorySegment struct, long fieldValue) {
        struct.set(tensorDescriptorAlignment$LAYOUT, tensorDescriptorAlignment$OFFSET, fieldValue);
    }

    private static final OfLong tensorCaptureReplayOpaqueDataSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("tensorCaptureReplayOpaqueDataSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t tensorCaptureReplayOpaqueDataSize
     * }
     */
    public static final OfLong tensorCaptureReplayOpaqueDataSize$layout() {
        return tensorCaptureReplayOpaqueDataSize$LAYOUT;
    }

    private static final long tensorCaptureReplayOpaqueDataSize$OFFSET = $LAYOUT.byteOffset(groupElement("tensorCaptureReplayOpaqueDataSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t tensorCaptureReplayOpaqueDataSize
     * }
     */
    public static final long tensorCaptureReplayOpaqueDataSize$offset() {
        return tensorCaptureReplayOpaqueDataSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t tensorCaptureReplayOpaqueDataSize
     * }
     */
    public static long tensorCaptureReplayOpaqueDataSize(MemorySegment struct) {
        return struct.get(tensorCaptureReplayOpaqueDataSize$LAYOUT, tensorCaptureReplayOpaqueDataSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t tensorCaptureReplayOpaqueDataSize
     * }
     */
    public static void tensorCaptureReplayOpaqueDataSize(MemorySegment struct, long fieldValue) {
        struct.set(tensorCaptureReplayOpaqueDataSize$LAYOUT, tensorCaptureReplayOpaqueDataSize$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

