// Generated by jextract

package fr.dufrenoy.hvt.runtime.vulkan;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VkPhysicalDeviceDescriptorHeapPropertiesEXT {
 *     VkStructureType sType;
 *     void *pNext;
 *     VkDeviceSize samplerHeapAlignment;
 *     VkDeviceSize resourceHeapAlignment;
 *     VkDeviceSize maxSamplerHeapSize;
 *     VkDeviceSize maxResourceHeapSize;
 *     VkDeviceSize minSamplerHeapReservedRange;
 *     VkDeviceSize minSamplerHeapReservedRangeWithEmbedded;
 *     VkDeviceSize minResourceHeapReservedRange;
 *     VkDeviceSize samplerDescriptorSize;
 *     VkDeviceSize imageDescriptorSize;
 *     VkDeviceSize bufferDescriptorSize;
 *     VkDeviceSize samplerDescriptorAlignment;
 *     VkDeviceSize imageDescriptorAlignment;
 *     VkDeviceSize bufferDescriptorAlignment;
 *     VkDeviceSize maxPushDataSize;
 *     size_t imageCaptureReplayOpaqueDataSize;
 *     uint32_t maxDescriptorHeapEmbeddedSamplers;
 *     uint32_t samplerYcbcrConversionCount;
 *     VkBool32 sparseDescriptorHeaps;
 *     VkBool32 protectedDescriptorHeaps;
 * }
 * }
 */
public class VkPhysicalDeviceDescriptorHeapPropertiesEXT {

    VkPhysicalDeviceDescriptorHeapPropertiesEXT() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        vulkan_h.C_INT.withName("sType"),
        MemoryLayout.paddingLayout(4),
        vulkan_h.C_POINTER.withName("pNext"),
        vulkan_h.C_LONG_LONG.withName("samplerHeapAlignment"),
        vulkan_h.C_LONG_LONG.withName("resourceHeapAlignment"),
        vulkan_h.C_LONG_LONG.withName("maxSamplerHeapSize"),
        vulkan_h.C_LONG_LONG.withName("maxResourceHeapSize"),
        vulkan_h.C_LONG_LONG.withName("minSamplerHeapReservedRange"),
        vulkan_h.C_LONG_LONG.withName("minSamplerHeapReservedRangeWithEmbedded"),
        vulkan_h.C_LONG_LONG.withName("minResourceHeapReservedRange"),
        vulkan_h.C_LONG_LONG.withName("samplerDescriptorSize"),
        vulkan_h.C_LONG_LONG.withName("imageDescriptorSize"),
        vulkan_h.C_LONG_LONG.withName("bufferDescriptorSize"),
        vulkan_h.C_LONG_LONG.withName("samplerDescriptorAlignment"),
        vulkan_h.C_LONG_LONG.withName("imageDescriptorAlignment"),
        vulkan_h.C_LONG_LONG.withName("bufferDescriptorAlignment"),
        vulkan_h.C_LONG_LONG.withName("maxPushDataSize"),
        vulkan_h.C_LONG_LONG.withName("imageCaptureReplayOpaqueDataSize"),
        vulkan_h.C_INT.withName("maxDescriptorHeapEmbeddedSamplers"),
        vulkan_h.C_INT.withName("samplerYcbcrConversionCount"),
        vulkan_h.C_INT.withName("sparseDescriptorHeaps"),
        vulkan_h.C_INT.withName("protectedDescriptorHeaps")
    ).withName("VkPhysicalDeviceDescriptorHeapPropertiesEXT");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt sType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final OfInt sType$layout() {
        return sType$LAYOUT;
    }

    private static final long sType$OFFSET = $LAYOUT.byteOffset(groupElement("sType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static final long sType$offset() {
        return sType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static int sType(MemorySegment struct) {
        return struct.get(sType$LAYOUT, sType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkStructureType sType
     * }
     */
    public static void sType(MemorySegment struct, int fieldValue) {
        struct.set(sType$LAYOUT, sType$OFFSET, fieldValue);
    }

    private static final AddressLayout pNext$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pNext"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static final AddressLayout pNext$layout() {
        return pNext$LAYOUT;
    }

    private static final long pNext$OFFSET = $LAYOUT.byteOffset(groupElement("pNext"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static final long pNext$offset() {
        return pNext$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static MemorySegment pNext(MemorySegment struct) {
        return struct.get(pNext$LAYOUT, pNext$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *pNext
     * }
     */
    public static void pNext(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pNext$LAYOUT, pNext$OFFSET, fieldValue);
    }

    private static final OfLong samplerHeapAlignment$LAYOUT = (OfLong)$LAYOUT.select(groupElement("samplerHeapAlignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerHeapAlignment
     * }
     */
    public static final OfLong samplerHeapAlignment$layout() {
        return samplerHeapAlignment$LAYOUT;
    }

    private static final long samplerHeapAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("samplerHeapAlignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerHeapAlignment
     * }
     */
    public static final long samplerHeapAlignment$offset() {
        return samplerHeapAlignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerHeapAlignment
     * }
     */
    public static long samplerHeapAlignment(MemorySegment struct) {
        return struct.get(samplerHeapAlignment$LAYOUT, samplerHeapAlignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerHeapAlignment
     * }
     */
    public static void samplerHeapAlignment(MemorySegment struct, long fieldValue) {
        struct.set(samplerHeapAlignment$LAYOUT, samplerHeapAlignment$OFFSET, fieldValue);
    }

    private static final OfLong resourceHeapAlignment$LAYOUT = (OfLong)$LAYOUT.select(groupElement("resourceHeapAlignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize resourceHeapAlignment
     * }
     */
    public static final OfLong resourceHeapAlignment$layout() {
        return resourceHeapAlignment$LAYOUT;
    }

    private static final long resourceHeapAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("resourceHeapAlignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize resourceHeapAlignment
     * }
     */
    public static final long resourceHeapAlignment$offset() {
        return resourceHeapAlignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize resourceHeapAlignment
     * }
     */
    public static long resourceHeapAlignment(MemorySegment struct) {
        return struct.get(resourceHeapAlignment$LAYOUT, resourceHeapAlignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize resourceHeapAlignment
     * }
     */
    public static void resourceHeapAlignment(MemorySegment struct, long fieldValue) {
        struct.set(resourceHeapAlignment$LAYOUT, resourceHeapAlignment$OFFSET, fieldValue);
    }

    private static final OfLong maxSamplerHeapSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("maxSamplerHeapSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize maxSamplerHeapSize
     * }
     */
    public static final OfLong maxSamplerHeapSize$layout() {
        return maxSamplerHeapSize$LAYOUT;
    }

    private static final long maxSamplerHeapSize$OFFSET = $LAYOUT.byteOffset(groupElement("maxSamplerHeapSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize maxSamplerHeapSize
     * }
     */
    public static final long maxSamplerHeapSize$offset() {
        return maxSamplerHeapSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize maxSamplerHeapSize
     * }
     */
    public static long maxSamplerHeapSize(MemorySegment struct) {
        return struct.get(maxSamplerHeapSize$LAYOUT, maxSamplerHeapSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize maxSamplerHeapSize
     * }
     */
    public static void maxSamplerHeapSize(MemorySegment struct, long fieldValue) {
        struct.set(maxSamplerHeapSize$LAYOUT, maxSamplerHeapSize$OFFSET, fieldValue);
    }

    private static final OfLong maxResourceHeapSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("maxResourceHeapSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize maxResourceHeapSize
     * }
     */
    public static final OfLong maxResourceHeapSize$layout() {
        return maxResourceHeapSize$LAYOUT;
    }

    private static final long maxResourceHeapSize$OFFSET = $LAYOUT.byteOffset(groupElement("maxResourceHeapSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize maxResourceHeapSize
     * }
     */
    public static final long maxResourceHeapSize$offset() {
        return maxResourceHeapSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize maxResourceHeapSize
     * }
     */
    public static long maxResourceHeapSize(MemorySegment struct) {
        return struct.get(maxResourceHeapSize$LAYOUT, maxResourceHeapSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize maxResourceHeapSize
     * }
     */
    public static void maxResourceHeapSize(MemorySegment struct, long fieldValue) {
        struct.set(maxResourceHeapSize$LAYOUT, maxResourceHeapSize$OFFSET, fieldValue);
    }

    private static final OfLong minSamplerHeapReservedRange$LAYOUT = (OfLong)$LAYOUT.select(groupElement("minSamplerHeapReservedRange"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize minSamplerHeapReservedRange
     * }
     */
    public static final OfLong minSamplerHeapReservedRange$layout() {
        return minSamplerHeapReservedRange$LAYOUT;
    }

    private static final long minSamplerHeapReservedRange$OFFSET = $LAYOUT.byteOffset(groupElement("minSamplerHeapReservedRange"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize minSamplerHeapReservedRange
     * }
     */
    public static final long minSamplerHeapReservedRange$offset() {
        return minSamplerHeapReservedRange$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize minSamplerHeapReservedRange
     * }
     */
    public static long minSamplerHeapReservedRange(MemorySegment struct) {
        return struct.get(minSamplerHeapReservedRange$LAYOUT, minSamplerHeapReservedRange$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize minSamplerHeapReservedRange
     * }
     */
    public static void minSamplerHeapReservedRange(MemorySegment struct, long fieldValue) {
        struct.set(minSamplerHeapReservedRange$LAYOUT, minSamplerHeapReservedRange$OFFSET, fieldValue);
    }

    private static final OfLong minSamplerHeapReservedRangeWithEmbedded$LAYOUT = (OfLong)$LAYOUT.select(groupElement("minSamplerHeapReservedRangeWithEmbedded"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize minSamplerHeapReservedRangeWithEmbedded
     * }
     */
    public static final OfLong minSamplerHeapReservedRangeWithEmbedded$layout() {
        return minSamplerHeapReservedRangeWithEmbedded$LAYOUT;
    }

    private static final long minSamplerHeapReservedRangeWithEmbedded$OFFSET = $LAYOUT.byteOffset(groupElement("minSamplerHeapReservedRangeWithEmbedded"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize minSamplerHeapReservedRangeWithEmbedded
     * }
     */
    public static final long minSamplerHeapReservedRangeWithEmbedded$offset() {
        return minSamplerHeapReservedRangeWithEmbedded$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize minSamplerHeapReservedRangeWithEmbedded
     * }
     */
    public static long minSamplerHeapReservedRangeWithEmbedded(MemorySegment struct) {
        return struct.get(minSamplerHeapReservedRangeWithEmbedded$LAYOUT, minSamplerHeapReservedRangeWithEmbedded$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize minSamplerHeapReservedRangeWithEmbedded
     * }
     */
    public static void minSamplerHeapReservedRangeWithEmbedded(MemorySegment struct, long fieldValue) {
        struct.set(minSamplerHeapReservedRangeWithEmbedded$LAYOUT, minSamplerHeapReservedRangeWithEmbedded$OFFSET, fieldValue);
    }

    private static final OfLong minResourceHeapReservedRange$LAYOUT = (OfLong)$LAYOUT.select(groupElement("minResourceHeapReservedRange"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize minResourceHeapReservedRange
     * }
     */
    public static final OfLong minResourceHeapReservedRange$layout() {
        return minResourceHeapReservedRange$LAYOUT;
    }

    private static final long minResourceHeapReservedRange$OFFSET = $LAYOUT.byteOffset(groupElement("minResourceHeapReservedRange"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize minResourceHeapReservedRange
     * }
     */
    public static final long minResourceHeapReservedRange$offset() {
        return minResourceHeapReservedRange$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize minResourceHeapReservedRange
     * }
     */
    public static long minResourceHeapReservedRange(MemorySegment struct) {
        return struct.get(minResourceHeapReservedRange$LAYOUT, minResourceHeapReservedRange$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize minResourceHeapReservedRange
     * }
     */
    public static void minResourceHeapReservedRange(MemorySegment struct, long fieldValue) {
        struct.set(minResourceHeapReservedRange$LAYOUT, minResourceHeapReservedRange$OFFSET, fieldValue);
    }

    private static final OfLong samplerDescriptorSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("samplerDescriptorSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerDescriptorSize
     * }
     */
    public static final OfLong samplerDescriptorSize$layout() {
        return samplerDescriptorSize$LAYOUT;
    }

    private static final long samplerDescriptorSize$OFFSET = $LAYOUT.byteOffset(groupElement("samplerDescriptorSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerDescriptorSize
     * }
     */
    public static final long samplerDescriptorSize$offset() {
        return samplerDescriptorSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerDescriptorSize
     * }
     */
    public static long samplerDescriptorSize(MemorySegment struct) {
        return struct.get(samplerDescriptorSize$LAYOUT, samplerDescriptorSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerDescriptorSize
     * }
     */
    public static void samplerDescriptorSize(MemorySegment struct, long fieldValue) {
        struct.set(samplerDescriptorSize$LAYOUT, samplerDescriptorSize$OFFSET, fieldValue);
    }

    private static final OfLong imageDescriptorSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("imageDescriptorSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize imageDescriptorSize
     * }
     */
    public static final OfLong imageDescriptorSize$layout() {
        return imageDescriptorSize$LAYOUT;
    }

    private static final long imageDescriptorSize$OFFSET = $LAYOUT.byteOffset(groupElement("imageDescriptorSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize imageDescriptorSize
     * }
     */
    public static final long imageDescriptorSize$offset() {
        return imageDescriptorSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize imageDescriptorSize
     * }
     */
    public static long imageDescriptorSize(MemorySegment struct) {
        return struct.get(imageDescriptorSize$LAYOUT, imageDescriptorSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize imageDescriptorSize
     * }
     */
    public static void imageDescriptorSize(MemorySegment struct, long fieldValue) {
        struct.set(imageDescriptorSize$LAYOUT, imageDescriptorSize$OFFSET, fieldValue);
    }

    private static final OfLong bufferDescriptorSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("bufferDescriptorSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize bufferDescriptorSize
     * }
     */
    public static final OfLong bufferDescriptorSize$layout() {
        return bufferDescriptorSize$LAYOUT;
    }

    private static final long bufferDescriptorSize$OFFSET = $LAYOUT.byteOffset(groupElement("bufferDescriptorSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize bufferDescriptorSize
     * }
     */
    public static final long bufferDescriptorSize$offset() {
        return bufferDescriptorSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize bufferDescriptorSize
     * }
     */
    public static long bufferDescriptorSize(MemorySegment struct) {
        return struct.get(bufferDescriptorSize$LAYOUT, bufferDescriptorSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize bufferDescriptorSize
     * }
     */
    public static void bufferDescriptorSize(MemorySegment struct, long fieldValue) {
        struct.set(bufferDescriptorSize$LAYOUT, bufferDescriptorSize$OFFSET, fieldValue);
    }

    private static final OfLong samplerDescriptorAlignment$LAYOUT = (OfLong)$LAYOUT.select(groupElement("samplerDescriptorAlignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerDescriptorAlignment
     * }
     */
    public static final OfLong samplerDescriptorAlignment$layout() {
        return samplerDescriptorAlignment$LAYOUT;
    }

    private static final long samplerDescriptorAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("samplerDescriptorAlignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerDescriptorAlignment
     * }
     */
    public static final long samplerDescriptorAlignment$offset() {
        return samplerDescriptorAlignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerDescriptorAlignment
     * }
     */
    public static long samplerDescriptorAlignment(MemorySegment struct) {
        return struct.get(samplerDescriptorAlignment$LAYOUT, samplerDescriptorAlignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize samplerDescriptorAlignment
     * }
     */
    public static void samplerDescriptorAlignment(MemorySegment struct, long fieldValue) {
        struct.set(samplerDescriptorAlignment$LAYOUT, samplerDescriptorAlignment$OFFSET, fieldValue);
    }

    private static final OfLong imageDescriptorAlignment$LAYOUT = (OfLong)$LAYOUT.select(groupElement("imageDescriptorAlignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize imageDescriptorAlignment
     * }
     */
    public static final OfLong imageDescriptorAlignment$layout() {
        return imageDescriptorAlignment$LAYOUT;
    }

    private static final long imageDescriptorAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("imageDescriptorAlignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize imageDescriptorAlignment
     * }
     */
    public static final long imageDescriptorAlignment$offset() {
        return imageDescriptorAlignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize imageDescriptorAlignment
     * }
     */
    public static long imageDescriptorAlignment(MemorySegment struct) {
        return struct.get(imageDescriptorAlignment$LAYOUT, imageDescriptorAlignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize imageDescriptorAlignment
     * }
     */
    public static void imageDescriptorAlignment(MemorySegment struct, long fieldValue) {
        struct.set(imageDescriptorAlignment$LAYOUT, imageDescriptorAlignment$OFFSET, fieldValue);
    }

    private static final OfLong bufferDescriptorAlignment$LAYOUT = (OfLong)$LAYOUT.select(groupElement("bufferDescriptorAlignment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize bufferDescriptorAlignment
     * }
     */
    public static final OfLong bufferDescriptorAlignment$layout() {
        return bufferDescriptorAlignment$LAYOUT;
    }

    private static final long bufferDescriptorAlignment$OFFSET = $LAYOUT.byteOffset(groupElement("bufferDescriptorAlignment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize bufferDescriptorAlignment
     * }
     */
    public static final long bufferDescriptorAlignment$offset() {
        return bufferDescriptorAlignment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize bufferDescriptorAlignment
     * }
     */
    public static long bufferDescriptorAlignment(MemorySegment struct) {
        return struct.get(bufferDescriptorAlignment$LAYOUT, bufferDescriptorAlignment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize bufferDescriptorAlignment
     * }
     */
    public static void bufferDescriptorAlignment(MemorySegment struct, long fieldValue) {
        struct.set(bufferDescriptorAlignment$LAYOUT, bufferDescriptorAlignment$OFFSET, fieldValue);
    }

    private static final OfLong maxPushDataSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("maxPushDataSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkDeviceSize maxPushDataSize
     * }
     */
    public static final OfLong maxPushDataSize$layout() {
        return maxPushDataSize$LAYOUT;
    }

    private static final long maxPushDataSize$OFFSET = $LAYOUT.byteOffset(groupElement("maxPushDataSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkDeviceSize maxPushDataSize
     * }
     */
    public static final long maxPushDataSize$offset() {
        return maxPushDataSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkDeviceSize maxPushDataSize
     * }
     */
    public static long maxPushDataSize(MemorySegment struct) {
        return struct.get(maxPushDataSize$LAYOUT, maxPushDataSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkDeviceSize maxPushDataSize
     * }
     */
    public static void maxPushDataSize(MemorySegment struct, long fieldValue) {
        struct.set(maxPushDataSize$LAYOUT, maxPushDataSize$OFFSET, fieldValue);
    }

    private static final OfLong imageCaptureReplayOpaqueDataSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("imageCaptureReplayOpaqueDataSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t imageCaptureReplayOpaqueDataSize
     * }
     */
    public static final OfLong imageCaptureReplayOpaqueDataSize$layout() {
        return imageCaptureReplayOpaqueDataSize$LAYOUT;
    }

    private static final long imageCaptureReplayOpaqueDataSize$OFFSET = $LAYOUT.byteOffset(groupElement("imageCaptureReplayOpaqueDataSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t imageCaptureReplayOpaqueDataSize
     * }
     */
    public static final long imageCaptureReplayOpaqueDataSize$offset() {
        return imageCaptureReplayOpaqueDataSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t imageCaptureReplayOpaqueDataSize
     * }
     */
    public static long imageCaptureReplayOpaqueDataSize(MemorySegment struct) {
        return struct.get(imageCaptureReplayOpaqueDataSize$LAYOUT, imageCaptureReplayOpaqueDataSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t imageCaptureReplayOpaqueDataSize
     * }
     */
    public static void imageCaptureReplayOpaqueDataSize(MemorySegment struct, long fieldValue) {
        struct.set(imageCaptureReplayOpaqueDataSize$LAYOUT, imageCaptureReplayOpaqueDataSize$OFFSET, fieldValue);
    }

    private static final OfInt maxDescriptorHeapEmbeddedSamplers$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maxDescriptorHeapEmbeddedSamplers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t maxDescriptorHeapEmbeddedSamplers
     * }
     */
    public static final OfInt maxDescriptorHeapEmbeddedSamplers$layout() {
        return maxDescriptorHeapEmbeddedSamplers$LAYOUT;
    }

    private static final long maxDescriptorHeapEmbeddedSamplers$OFFSET = $LAYOUT.byteOffset(groupElement("maxDescriptorHeapEmbeddedSamplers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t maxDescriptorHeapEmbeddedSamplers
     * }
     */
    public static final long maxDescriptorHeapEmbeddedSamplers$offset() {
        return maxDescriptorHeapEmbeddedSamplers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t maxDescriptorHeapEmbeddedSamplers
     * }
     */
    public static int maxDescriptorHeapEmbeddedSamplers(MemorySegment struct) {
        return struct.get(maxDescriptorHeapEmbeddedSamplers$LAYOUT, maxDescriptorHeapEmbeddedSamplers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t maxDescriptorHeapEmbeddedSamplers
     * }
     */
    public static void maxDescriptorHeapEmbeddedSamplers(MemorySegment struct, int fieldValue) {
        struct.set(maxDescriptorHeapEmbeddedSamplers$LAYOUT, maxDescriptorHeapEmbeddedSamplers$OFFSET, fieldValue);
    }

    private static final OfInt samplerYcbcrConversionCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("samplerYcbcrConversionCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t samplerYcbcrConversionCount
     * }
     */
    public static final OfInt samplerYcbcrConversionCount$layout() {
        return samplerYcbcrConversionCount$LAYOUT;
    }

    private static final long samplerYcbcrConversionCount$OFFSET = $LAYOUT.byteOffset(groupElement("samplerYcbcrConversionCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t samplerYcbcrConversionCount
     * }
     */
    public static final long samplerYcbcrConversionCount$offset() {
        return samplerYcbcrConversionCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t samplerYcbcrConversionCount
     * }
     */
    public static int samplerYcbcrConversionCount(MemorySegment struct) {
        return struct.get(samplerYcbcrConversionCount$LAYOUT, samplerYcbcrConversionCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t samplerYcbcrConversionCount
     * }
     */
    public static void samplerYcbcrConversionCount(MemorySegment struct, int fieldValue) {
        struct.set(samplerYcbcrConversionCount$LAYOUT, samplerYcbcrConversionCount$OFFSET, fieldValue);
    }

    private static final OfInt sparseDescriptorHeaps$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sparseDescriptorHeaps"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkBool32 sparseDescriptorHeaps
     * }
     */
    public static final OfInt sparseDescriptorHeaps$layout() {
        return sparseDescriptorHeaps$LAYOUT;
    }

    private static final long sparseDescriptorHeaps$OFFSET = $LAYOUT.byteOffset(groupElement("sparseDescriptorHeaps"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkBool32 sparseDescriptorHeaps
     * }
     */
    public static final long sparseDescriptorHeaps$offset() {
        return sparseDescriptorHeaps$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkBool32 sparseDescriptorHeaps
     * }
     */
    public static int sparseDescriptorHeaps(MemorySegment struct) {
        return struct.get(sparseDescriptorHeaps$LAYOUT, sparseDescriptorHeaps$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkBool32 sparseDescriptorHeaps
     * }
     */
    public static void sparseDescriptorHeaps(MemorySegment struct, int fieldValue) {
        struct.set(sparseDescriptorHeaps$LAYOUT, sparseDescriptorHeaps$OFFSET, fieldValue);
    }

    private static final OfInt protectedDescriptorHeaps$LAYOUT = (OfInt)$LAYOUT.select(groupElement("protectedDescriptorHeaps"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkBool32 protectedDescriptorHeaps
     * }
     */
    public static final OfInt protectedDescriptorHeaps$layout() {
        return protectedDescriptorHeaps$LAYOUT;
    }

    private static final long protectedDescriptorHeaps$OFFSET = $LAYOUT.byteOffset(groupElement("protectedDescriptorHeaps"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkBool32 protectedDescriptorHeaps
     * }
     */
    public static final long protectedDescriptorHeaps$offset() {
        return protectedDescriptorHeaps$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkBool32 protectedDescriptorHeaps
     * }
     */
    public static int protectedDescriptorHeaps(MemorySegment struct) {
        return struct.get(protectedDescriptorHeaps$LAYOUT, protectedDescriptorHeaps$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkBool32 protectedDescriptorHeaps
     * }
     */
    public static void protectedDescriptorHeaps(MemorySegment struct, int fieldValue) {
        struct.set(protectedDescriptorHeaps$LAYOUT, protectedDescriptorHeaps$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

