// Generated by jextract

package fr.dufrenoy.hvt.runtime.vulkan;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * union VkResourceDescriptorDataEXT {
 *     const VkImageDescriptorInfoEXT *pImage;
 *     const VkTexelBufferDescriptorInfoEXT *pTexelBuffer;
 *     const VkDeviceAddressRangeEXT *pAddressRange;
 *     const VkTensorViewCreateInfoARM *pTensorARM;
 * }
 * }
 */
public class VkResourceDescriptorDataEXT {

    VkResourceDescriptorDataEXT() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        vulkan_h.C_POINTER.withName("pImage"),
        vulkan_h.C_POINTER.withName("pTexelBuffer"),
        vulkan_h.C_POINTER.withName("pAddressRange"),
        vulkan_h.C_POINTER.withName("pTensorARM")
    ).withName("VkResourceDescriptorDataEXT");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout pImage$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pImage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const VkImageDescriptorInfoEXT *pImage
     * }
     */
    public static final AddressLayout pImage$layout() {
        return pImage$LAYOUT;
    }

    private static final long pImage$OFFSET = $LAYOUT.byteOffset(groupElement("pImage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const VkImageDescriptorInfoEXT *pImage
     * }
     */
    public static final long pImage$offset() {
        return pImage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const VkImageDescriptorInfoEXT *pImage
     * }
     */
    public static MemorySegment pImage(MemorySegment union) {
        return union.get(pImage$LAYOUT, pImage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const VkImageDescriptorInfoEXT *pImage
     * }
     */
    public static void pImage(MemorySegment union, MemorySegment fieldValue) {
        union.set(pImage$LAYOUT, pImage$OFFSET, fieldValue);
    }

    private static final AddressLayout pTexelBuffer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pTexelBuffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const VkTexelBufferDescriptorInfoEXT *pTexelBuffer
     * }
     */
    public static final AddressLayout pTexelBuffer$layout() {
        return pTexelBuffer$LAYOUT;
    }

    private static final long pTexelBuffer$OFFSET = $LAYOUT.byteOffset(groupElement("pTexelBuffer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const VkTexelBufferDescriptorInfoEXT *pTexelBuffer
     * }
     */
    public static final long pTexelBuffer$offset() {
        return pTexelBuffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const VkTexelBufferDescriptorInfoEXT *pTexelBuffer
     * }
     */
    public static MemorySegment pTexelBuffer(MemorySegment union) {
        return union.get(pTexelBuffer$LAYOUT, pTexelBuffer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const VkTexelBufferDescriptorInfoEXT *pTexelBuffer
     * }
     */
    public static void pTexelBuffer(MemorySegment union, MemorySegment fieldValue) {
        union.set(pTexelBuffer$LAYOUT, pTexelBuffer$OFFSET, fieldValue);
    }

    private static final AddressLayout pAddressRange$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pAddressRange"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const VkDeviceAddressRangeEXT *pAddressRange
     * }
     */
    public static final AddressLayout pAddressRange$layout() {
        return pAddressRange$LAYOUT;
    }

    private static final long pAddressRange$OFFSET = $LAYOUT.byteOffset(groupElement("pAddressRange"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const VkDeviceAddressRangeEXT *pAddressRange
     * }
     */
    public static final long pAddressRange$offset() {
        return pAddressRange$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const VkDeviceAddressRangeEXT *pAddressRange
     * }
     */
    public static MemorySegment pAddressRange(MemorySegment union) {
        return union.get(pAddressRange$LAYOUT, pAddressRange$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const VkDeviceAddressRangeEXT *pAddressRange
     * }
     */
    public static void pAddressRange(MemorySegment union, MemorySegment fieldValue) {
        union.set(pAddressRange$LAYOUT, pAddressRange$OFFSET, fieldValue);
    }

    private static final AddressLayout pTensorARM$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pTensorARM"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const VkTensorViewCreateInfoARM *pTensorARM
     * }
     */
    public static final AddressLayout pTensorARM$layout() {
        return pTensorARM$LAYOUT;
    }

    private static final long pTensorARM$OFFSET = $LAYOUT.byteOffset(groupElement("pTensorARM"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const VkTensorViewCreateInfoARM *pTensorARM
     * }
     */
    public static final long pTensorARM$offset() {
        return pTensorARM$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const VkTensorViewCreateInfoARM *pTensorARM
     * }
     */
    public static MemorySegment pTensorARM(MemorySegment union) {
        return union.get(pTensorARM$LAYOUT, pTensorARM$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const VkTensorViewCreateInfoARM *pTensorARM
     * }
     */
    public static void pTensorARM(MemorySegment union, MemorySegment fieldValue) {
        union.set(pTensorARM$LAYOUT, pTensorARM$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this union
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

