// Generated by jextract

package fr.dufrenoy.hvt.runtime.vulkan;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class vulkan_h extends vulkan_h_1 {

    vulkan_h() {
        // Should not be called directly
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_EXTERNAL_COMPUTE_QUEUE_EXTENSION_NAME "VK_NV_external_compute_queue"
     * }
     */
    public static MemorySegment VK_NV_EXTERNAL_COMPUTE_QUEUE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_EXTERNAL_COMPUTE_QUEUE_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_NV_external_compute_queue");
        }
        return Holder.VK_NV_EXTERNAL_COMPUTE_QUEUE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_COMMAND_BUFFER_INHERITANCE_EXTENSION_NAME "VK_NV_command_buffer_inheritance"
     * }
     */
    public static MemorySegment VK_NV_COMMAND_BUFFER_INHERITANCE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_COMMAND_BUFFER_INHERITANCE_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_NV_command_buffer_inheritance");
        }
        return Holder.VK_NV_COMMAND_BUFFER_INHERITANCE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_SHADER_ATOMIC_FLOAT16_VECTOR_EXTENSION_NAME "VK_NV_shader_atomic_float16_vector"
     * }
     */
    public static MemorySegment VK_NV_SHADER_ATOMIC_FLOAT16_VECTOR_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_SHADER_ATOMIC_FLOAT16_VECTOR_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_NV_shader_atomic_float16_vector");
        }
        return Holder.VK_NV_SHADER_ATOMIC_FLOAT16_VECTOR_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_REPLICATED_COMPOSITES_EXTENSION_NAME "VK_EXT_shader_replicated_composites"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_REPLICATED_COMPOSITES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_REPLICATED_COMPOSITES_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_replicated_composites");
        }
        return Holder.VK_EXT_SHADER_REPLICATED_COMPOSITES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_FLOAT8_EXTENSION_NAME "VK_EXT_shader_float8"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_FLOAT8_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_FLOAT8_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_float8");
        }
        return Holder.VK_EXT_SHADER_FLOAT8_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_RAY_TRACING_VALIDATION_EXTENSION_NAME "VK_NV_ray_tracing_validation"
     * }
     */
    public static MemorySegment VK_NV_RAY_TRACING_VALIDATION_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_RAY_TRACING_VALIDATION_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_NV_ray_tracing_validation");
        }
        return Holder.VK_NV_RAY_TRACING_VALIDATION_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME "VK_NV_cluster_acceleration_structure"
     * }
     */
    public static MemorySegment VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_NV_cluster_acceleration_structure");
        }
        return Holder.VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME "VK_NV_partitioned_acceleration_structure"
     * }
     */
    public static MemorySegment VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_NV_partitioned_acceleration_structure");
        }
        return Holder.VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME;
    }
    private static final int VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV 4294967295
     * }
     */
    public static int VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV() {
        return VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME "VK_EXT_device_generated_commands"
     * }
     */
    public static MemorySegment VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_device_generated_commands");
        }
        return Holder.VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_MESA_IMAGE_ALIGNMENT_CONTROL_EXTENSION_NAME "VK_MESA_image_alignment_control"
     * }
     */
    public static MemorySegment VK_MESA_IMAGE_ALIGNMENT_CONTROL_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_MESA_IMAGE_ALIGNMENT_CONTROL_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_MESA_image_alignment_control");
        }
        return Holder.VK_MESA_IMAGE_ALIGNMENT_CONTROL_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_PUSH_CONSTANT_BANK_EXTENSION_NAME "VK_NV_push_constant_bank"
     * }
     */
    public static MemorySegment VK_NV_PUSH_CONSTANT_BANK_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_PUSH_CONSTANT_BANK_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_NV_push_constant_bank");
        }
        return Holder.VK_NV_PUSH_CONSTANT_BANK_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME "VK_EXT_ray_tracing_invocation_reorder"
     * }
     */
    public static MemorySegment VK_EXT_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_ray_tracing_invocation_reorder");
        }
        return Holder.VK_EXT_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DEPTH_CLAMP_CONTROL_EXTENSION_NAME "VK_EXT_depth_clamp_control"
     * }
     */
    public static MemorySegment VK_EXT_DEPTH_CLAMP_CONTROL_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DEPTH_CLAMP_CONTROL_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_depth_clamp_control");
        }
        return Holder.VK_EXT_DEPTH_CLAMP_CONTROL_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_HUAWEI_HDR_VIVID_EXTENSION_NAME "VK_HUAWEI_hdr_vivid"
     * }
     */
    public static MemorySegment VK_HUAWEI_HDR_VIVID_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_HUAWEI_HDR_VIVID_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_HUAWEI_hdr_vivid");
        }
        return Holder.VK_HUAWEI_HDR_VIVID_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME "VK_NV_cooperative_matrix2"
     * }
     */
    public static MemorySegment VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_NV_cooperative_matrix2");
        }
        return Holder.VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_ARM_PIPELINE_OPACITY_MICROMAP_EXTENSION_NAME "VK_ARM_pipeline_opacity_micromap"
     * }
     */
    public static MemorySegment VK_ARM_PIPELINE_OPACITY_MICROMAP_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_ARM_PIPELINE_OPACITY_MICROMAP_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_ARM_pipeline_opacity_micromap");
        }
        return Holder.VK_ARM_PIPELINE_OPACITY_MICROMAP_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_ARM_PERFORMANCE_COUNTERS_BY_REGION_EXTENSION_NAME "VK_ARM_performance_counters_by_region"
     * }
     */
    public static MemorySegment VK_ARM_PERFORMANCE_COUNTERS_BY_REGION_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_ARM_PERFORMANCE_COUNTERS_BY_REGION_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_ARM_performance_counters_by_region");
        }
        return Holder.VK_ARM_PERFORMANCE_COUNTERS_BY_REGION_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_VERTEX_ATTRIBUTE_ROBUSTNESS_EXTENSION_NAME "VK_EXT_vertex_attribute_robustness"
     * }
     */
    public static MemorySegment VK_EXT_VERTEX_ATTRIBUTE_ROBUSTNESS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_VERTEX_ATTRIBUTE_ROBUSTNESS_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_vertex_attribute_robustness");
        }
        return Holder.VK_EXT_VERTEX_ATTRIBUTE_ROBUSTNESS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_ARM_FORMAT_PACK_EXTENSION_NAME "VK_ARM_format_pack"
     * }
     */
    public static MemorySegment VK_ARM_FORMAT_PACK_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_ARM_FORMAT_PACK_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_ARM_format_pack");
        }
        return Holder.VK_ARM_FORMAT_PACK_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_VALVE_FRAGMENT_DENSITY_MAP_LAYERED_EXTENSION_NAME "VK_VALVE_fragment_density_map_layered"
     * }
     */
    public static MemorySegment VK_VALVE_FRAGMENT_DENSITY_MAP_LAYERED_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_VALVE_FRAGMENT_DENSITY_MAP_LAYERED_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_VALVE_fragment_density_map_layered");
        }
        return Holder.VK_VALVE_FRAGMENT_DENSITY_MAP_LAYERED_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_PRESENT_METERING_EXTENSION_NAME "VK_NV_present_metering"
     * }
     */
    public static MemorySegment VK_NV_PRESENT_METERING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_PRESENT_METERING_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_NV_present_metering");
        }
        return Holder.VK_NV_PRESENT_METERING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_FRAGMENT_DENSITY_MAP_OFFSET_EXTENSION_NAME "VK_EXT_fragment_density_map_offset"
     * }
     */
    public static MemorySegment VK_EXT_FRAGMENT_DENSITY_MAP_OFFSET_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_FRAGMENT_DENSITY_MAP_OFFSET_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_fragment_density_map_offset");
        }
        return Holder.VK_EXT_FRAGMENT_DENSITY_MAP_OFFSET_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_ZERO_INITIALIZE_DEVICE_MEMORY_EXTENSION_NAME "VK_EXT_zero_initialize_device_memory"
     * }
     */
    public static MemorySegment VK_EXT_ZERO_INITIALIZE_DEVICE_MEMORY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_ZERO_INITIALIZE_DEVICE_MEMORY_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_zero_initialize_device_memory");
        }
        return Holder.VK_EXT_ZERO_INITIALIZE_DEVICE_MEMORY_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_64BIT_INDEXING_EXTENSION_NAME "VK_EXT_shader_64bit_indexing"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_64BIT_INDEXING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_64BIT_INDEXING_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_64bit_indexing");
        }
        return Holder.VK_EXT_SHADER_64BIT_INDEXING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_CUSTOM_RESOLVE_EXTENSION_NAME "VK_EXT_custom_resolve"
     * }
     */
    public static MemorySegment VK_EXT_CUSTOM_RESOLVE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_CUSTOM_RESOLVE_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_custom_resolve");
        }
        return Holder.VK_EXT_CUSTOM_RESOLVE_EXTENSION_NAME;
    }
    private static final int VK_DATA_GRAPH_MODEL_TOOLCHAIN_VERSION_LENGTH_QCOM = (int)3L;
    /**
     * {@snippet lang=c :
     * #define VK_DATA_GRAPH_MODEL_TOOLCHAIN_VERSION_LENGTH_QCOM 3
     * }
     */
    public static int VK_DATA_GRAPH_MODEL_TOOLCHAIN_VERSION_LENGTH_QCOM() {
        return VK_DATA_GRAPH_MODEL_TOOLCHAIN_VERSION_LENGTH_QCOM;
    }
    /**
     * {@snippet lang=c :
     * #define VK_QCOM_DATA_GRAPH_MODEL_EXTENSION_NAME "VK_QCOM_data_graph_model"
     * }
     */
    public static MemorySegment VK_QCOM_DATA_GRAPH_MODEL_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_QCOM_DATA_GRAPH_MODEL_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_QCOM_data_graph_model");
        }
        return Holder.VK_QCOM_DATA_GRAPH_MODEL_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_LONG_VECTOR_EXTENSION_NAME "VK_EXT_shader_long_vector"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_LONG_VECTOR_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_LONG_VECTOR_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_long_vector");
        }
        return Holder.VK_EXT_SHADER_LONG_VECTOR_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_SEC_PIPELINE_CACHE_INCREMENTAL_MODE_EXTENSION_NAME "VK_SEC_pipeline_cache_incremental_mode"
     * }
     */
    public static MemorySegment VK_SEC_PIPELINE_CACHE_INCREMENTAL_MODE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_SEC_PIPELINE_CACHE_INCREMENTAL_MODE_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_SEC_pipeline_cache_incremental_mode");
        }
        return Holder.VK_SEC_PIPELINE_CACHE_INCREMENTAL_MODE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_UNIFORM_BUFFER_UNSIZED_ARRAY_EXTENSION_NAME "VK_EXT_shader_uniform_buffer_unsized_array"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_UNIFORM_BUFFER_UNSIZED_ARRAY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_UNIFORM_BUFFER_UNSIZED_ARRAY_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_uniform_buffer_unsized_array");
        }
        return Holder.VK_EXT_SHADER_UNIFORM_BUFFER_UNSIZED_ARRAY_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_COMPUTE_OCCUPANCY_PRIORITY_EXTENSION_NAME "VK_NV_compute_occupancy_priority"
     * }
     */
    public static MemorySegment VK_NV_COMPUTE_OCCUPANCY_PRIORITY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_COMPUTE_OCCUPANCY_PRIORITY_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_NV_compute_occupancy_priority");
        }
        return Holder.VK_NV_COMPUTE_OCCUPANCY_PRIORITY_EXTENSION_NAME;
    }
    private static final float VK_COMPUTE_OCCUPANCY_PRIORITY_LOW_NV = 0.25f;
    /**
     * {@snippet lang=c :
     * #define VK_COMPUTE_OCCUPANCY_PRIORITY_LOW_NV 0.25
     * }
     */
    public static float VK_COMPUTE_OCCUPANCY_PRIORITY_LOW_NV() {
        return VK_COMPUTE_OCCUPANCY_PRIORITY_LOW_NV;
    }
    private static final float VK_COMPUTE_OCCUPANCY_PRIORITY_NORMAL_NV = 0.5f;
    /**
     * {@snippet lang=c :
     * #define VK_COMPUTE_OCCUPANCY_PRIORITY_NORMAL_NV 0.5
     * }
     */
    public static float VK_COMPUTE_OCCUPANCY_PRIORITY_NORMAL_NV() {
        return VK_COMPUTE_OCCUPANCY_PRIORITY_NORMAL_NV;
    }
    private static final float VK_COMPUTE_OCCUPANCY_PRIORITY_HIGH_NV = 0.75f;
    /**
     * {@snippet lang=c :
     * #define VK_COMPUTE_OCCUPANCY_PRIORITY_HIGH_NV 0.75
     * }
     */
    public static float VK_COMPUTE_OCCUPANCY_PRIORITY_HIGH_NV() {
        return VK_COMPUTE_OCCUPANCY_PRIORITY_HIGH_NV;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_SUBGROUP_PARTITIONED_EXTENSION_NAME "VK_EXT_shader_subgroup_partitioned"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_SUBGROUP_PARTITIONED_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_SUBGROUP_PARTITIONED_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_subgroup_partitioned");
        }
        return Holder.VK_EXT_SHADER_SUBGROUP_PARTITIONED_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME "VK_KHR_acceleration_structure"
     * }
     */
    public static MemorySegment VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_KHR_acceleration_structure");
        }
        return Holder.VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME "VK_KHR_ray_tracing_pipeline"
     * }
     */
    public static MemorySegment VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_KHR_ray_tracing_pipeline");
        }
        return Holder.VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_KHR_RAY_QUERY_EXTENSION_NAME "VK_KHR_ray_query"
     * }
     */
    public static MemorySegment VK_KHR_RAY_QUERY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_KHR_RAY_QUERY_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_KHR_ray_query");
        }
        return Holder.VK_KHR_RAY_QUERY_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_MESH_SHADER_EXTENSION_NAME "VK_EXT_mesh_shader"
     * }
     */
    public static MemorySegment VK_EXT_MESH_SHADER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_MESH_SHADER_EXTENSION_NAME
                = vulkan_h.LIBRARY_ARENA.allocateFrom("VK_EXT_mesh_shader");
        }
        return Holder.VK_EXT_MESH_SHADER_EXTENSION_NAME;
    }
}

